#baseURL = 'https://volteret4.github.io/vvmm/'
baseURL = "/"
languageCode = 'es-ES'
title = 'vvmm'
theme = 'hugo-theme-m10c'
staticDir = ['static']
favicon = 'favicon.ico'

[pagination]
    pagerSize = 15

[menu]
    [[menu.main]]
        identifier = "home"
        name = "discos"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = 'tags'
        name = "generos"
        url = "/tags/"
        weight= 2
    [[menu.main]]
        identifier = "coleccion"
        name = "colecci√≥n"
        url = "/coleccion/"
        weight = 3

#[menu]
#  [[menu.main]]
#    identifier = "home"
#    name = "Home"
#    url = "/"
#    weight = 1
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"
#    weight = 2
#  [[menu.main]]
#    name = "All posts"
#    url = "/posts"
#    weight = 3

[params]
#  mode = 'dark'
    author = 'pollo'
    description = 'descubrimientos sonoros'
    menu_item_separator = " - "
    avatar = 'avatar.jpg'
    [[params.social]]
        icon = "brand-github"
        name = "Github"
        url = "https://github.com/volteret4"
#  columns = 2
#  mainSections = ["posts"]
#  dateFormat = "January 02, 2006"
#  colorTheme = "dark-blue"
#  mainMenuAlignment = "right"
#  authorbox = false
#  related = true

#[Params.Share] # Entry Share block
#  twitter = true
#  reddit = true
#  telegram = true
#  pocket = true


#[[params.social]]
#    icon = "github"			## m10c theme conf
#    name = "My Github"
#    url = "https://github.com/volteret4"


# Green theme
[params.style]
    darkestColor = "#1a1a22"
    darkColor = "#1f1f28"
    lightColor = "#a06d9c"
    lightestColor = "#fff"
    primaryColor = "#caa5f6"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
